"""
Adaptive AI Assessment Engine
------------------------------
Upgrades the existing static question bank (app/ai/question_bank.py, kept
untouched and used as the fallback pool) into a step-by-step adaptive flow:

    correct answer  -> increase difficulty, move to next weak topic
    wrong answer    -> decrease difficulty, ask a diagnostic follow-up on the
                       SAME topic, and record it as an identified weakness

Each question is generated by the AI provider when configured; if the AI
call fails or is unavailable, a question is drawn from the existing
deterministic question bank instead — the session keeps going either way.
"""
import random

from pydantic import ValidationError

from app.ai.ai_provider import ai_provider
from app.ai.prompts.assessment_prompt import SYSTEM_PROMPT, build_prompt
from app.ai.schemas.ai_schemas import AdaptiveQuestion
from app.ai import question_bank

DIFFICULTY_ORDER = ["beginner", "intermediate", "advanced"]
DEFAULT_MAX_STEPS = 5


def initial_topic(topic_scores: dict[str, float] | None, skill_name: str) -> str:
    if topic_scores:
        return question_bank.weakest_topics(topic_scores, top_n=1)[0]
    bank_topics = list(question_bank.QUESTION_BANK.get(skill_name, {}).keys())
    return bank_topics[0] if bank_topics else "General"


def next_difficulty(current: str, was_correct: bool | None) -> str:
    if was_correct is None:
        return current
    idx = DIFFICULTY_ORDER.index(current) if current in DIFFICULTY_ORDER else 1
    if was_correct:
        idx = min(idx + 1, len(DIFFICULTY_ORDER) - 1)
    else:
        idx = max(idx - 1, 0)
    return DIFFICULTY_ORDER[idx]


def _fallback_question(skill_name: str, topic: str, difficulty: str) -> dict:
    pool = question_bank.generate_questions(skill_name, [topic], 1)
    q = pool[0]
    return {
        "topic": q["topic"], "difficulty": difficulty, "question_type": q["question_type"],
        "prompt": q["prompt"], "options": q["options"], "correct_answer": q["correct_answer"],
        "explanation": q["explanation"],
    }


async def generate_question(skill_name: str, topic: str, difficulty: str) -> tuple[dict, bool]:
    """Returns (question_dict, used_ai)."""
    ai_json = await ai_provider.generate_json(build_prompt(skill_name, topic, difficulty), SYSTEM_PROMPT)
    if ai_json is not None:
        try:
            q = AdaptiveQuestion(**ai_json)
            return q.model_dump(), True
        except ValidationError:
            pass
    return _fallback_question(skill_name, topic, difficulty), False


def pick_next_topic(skill_name: str, current_topic: str, was_correct: bool) -> str:
    """Wrong -> stay on the same topic (diagnostic). Correct -> rotate to another topic."""
    if not was_correct:
        return current_topic
    topics = list(question_bank.QUESTION_BANK.get(skill_name, {}).keys()) or [current_topic]
    others = [t for t in topics if t != current_topic]
    return random.choice(others) if others else current_topic
