"""initial schema with ai models

Revision ID: 0fd63c8891a3
Revises: 
Create Date: 2026-09-01 08:47:04.962505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd63c8891a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'college', 'industry', 'admin', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('college_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('industry_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry_sector', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_skill_id'), 'questions', ['skill_id'], unique=False)
    op.create_table('role_skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('target_proficiency', sa.Float(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['career_roles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_skill_requirements_role_id'), 'role_skill_requirements', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_skill_requirements_skill_id'), 'role_skill_requirements', ['skill_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('min_year_of_study', sa.Integer(), nullable=False),
    sa.Column('final_year_only', sa.Integer(), nullable=False),
    sa.Column('stipend_or_ctc', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_industry_id'), 'opportunities', ['industry_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('career_goal', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('profile_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('adaptive_assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_topic', sa.String(length=120), nullable=False),
    sa.Column('current_difficulty', sa.String(length=20), nullable=False),
    sa.Column('current_question', sa.JSON(), nullable=False),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('weak_topics', sa.JSON(), nullable=False),
    sa.Column('used_ai_any', sa.Boolean(), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptive_assessment_sessions_skill_id'), 'adaptive_assessment_sessions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_adaptive_assessment_sessions_student_id'), 'adaptive_assessment_sessions', ['student_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('used_data_points', sa.JSON(), nullable=False),
    sa.Column('used_ai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_student_id'), 'ai_conversations', ['student_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_explanation', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('topic_focus', sa.String(length=255), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_attempts_skill_id'), 'assessment_attempts', ['skill_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_student_id'), 'assessment_attempts', ['student_id'], unique=False)
    op.create_table('github_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('used_ai', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_analyses_student_id'), 'github_analyses', ['student_id'], unique=False)
    op.create_table('opportunity_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('min_proficiency', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_skills_opportunity_id'), 'opportunity_skills', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_skills_skill_id'), 'opportunity_skills', ['skill_id'], unique=False)
    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('used_ai', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_analyses_student_id'), 'resume_analyses', ['student_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_skill_id'), 'roadmap_steps', ['skill_id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_student_id'), 'roadmap_steps', ['student_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skills_skill_id'), 'student_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_skill_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_skill_id'], ['student_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_student_skill_id'), 'evidence', ['student_skill_id'], unique=False)
    op.create_table('industry_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('technical_skill', sa.Float(), nullable=False),
    sa.Column('problem_solving', sa.Float(), nullable=False),
    sa.Column('communication', sa.Float(), nullable=False),
    sa.Column('teamwork', sa.Float(), nullable=False),
    sa.Column('professionalism', sa.Float(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('skill_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_skill_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['student_skill_id'], ['student_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_score_history_student_skill_id'), 'skill_score_history', ['student_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_score_history_student_skill_id'), table_name='skill_score_history')
    op.drop_table('skill_score_history')
    op.drop_table('industry_feedback')
    op.drop_index(op.f('ix_evidence_student_skill_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_skill_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_roadmap_steps_student_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_skill_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_resume_analyses_student_id'), table_name='resume_analyses')
    op.drop_table('resume_analyses')
    op.drop_index(op.f('ix_opportunity_skills_skill_id'), table_name='opportunity_skills')
    op.drop_index(op.f('ix_opportunity_skills_opportunity_id'), table_name='opportunity_skills')
    op.drop_table('opportunity_skills')
    op.drop_index(op.f('ix_github_analyses_student_id'), table_name='github_analyses')
    op.drop_table('github_analyses')
    op.drop_index(op.f('ix_assessment_attempts_student_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_skill_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_ai_conversations_student_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_adaptive_assessment_sessions_student_id'), table_name='adaptive_assessment_sessions')
    op.drop_index(op.f('ix_adaptive_assessment_sessions_skill_id'), table_name='adaptive_assessment_sessions')
    op.drop_table('adaptive_assessment_sessions')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_opportunities_industry_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_role_skill_requirements_skill_id'), table_name='role_skill_requirements')
    op.drop_index(op.f('ix_role_skill_requirements_role_id'), table_name='role_skill_requirements')
    op.drop_table('role_skill_requirements')
    op.drop_index(op.f('ix_questions_skill_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('industry_profiles')
    op.drop_table('college_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('career_roles')
    # ### end Alembic commands ###
